### ISSUE TITLE
More suggestions

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#18]
Maybe things from https://twitter.com/DrapsTV/status/660657599210266624 can be reused (maybe not).

**Comment by SylvainDe** [comment]
A few ideas from http://migrateup.com/main-difference-python-3/ are interesting too.

**Comment by SylvainDe** [comment]
http://www.oreilly.com/programming/free/how-to-make-mistakes-in-python.csp /http://www.oreilly.com/programming/free/files/how-to-make-mistakes-in-python.pdf

**Comment by SylvainDe** [comment]
Probably worth re-reading http://stupidpythonideas.blogspot.fr/2015/05/if-you-dont-like-exceptions-you-dont.html ( and http://stupidpythonideas.blogspot.fr/2015/12/how-lookup-works.html ) when I have more time.

**Comment by SylvainDe** [comment]
https://github.com/mdipierro/autoinstaller : interesting idea. I'll try to understand the code and see if I can reuse ideas out of it.

Also, it could be nice to make things usable with the -m option ( http://python-packaging.readthedocs.org/en/latest/command-line-scripts.html / https://www.reddit.com/r/Python/comments/42u5dm/how_to_structure_a_module_that_is_intended_to_be/ ).

**Comment by SylvainDe** [comment]
https://github.com/bndr/pipreqs/blob/master/pipreqs/pipreqs.py

**Comment by SylvainDe** [comment]
Principle of Least Astonishment and Python : http://lucumr.pocoo.org/2011/7/9/python-and-pola/ .

A few suggestions might make sense.

**Comment by SylvainDe** [comment]
Confusing/interesting error messages here : https://www.reddit.com/r/Python/comments/4ivd2k/what_is_your_favorite_python_error_message/

**Comment by SylvainDe** [comment]
https://github.com/asweigart/pydidyoumean

**Comment by SylvainDe** [comment]
I've just discovered the change about literal octals in Python 3. Might be interesting to have a suggestion.

**Comment by SylvainDe** [comment]
https://twitter.com/raymondh/status/772957699478663169
"#python tip: What Python says: "TypeError: 'method' object is not subscriptable" What it means: "Use parentheses instead of square brackets""

https://twitter.com/raymondh/status/773224135409360896
"What #Python says: TypeError: 'Tk' object cannot be interpreted as an integer What it means: class 'Tk' does not have an __index__ method"

**Comment by SylvainDe** [comment]
http://stackoverflow.com/questions/38147923/mixing-datetime-strptime-arguments/38215307 pretty common error: mixing argument of `strptime`.

https://twitter.com/brandon_rhodes/status/781234730091941888

**Comment by SylvainDe** [comment]
SyntaxError: `if a = b:` and `if a == b`

**Comment by SylvainDe** [comment]
https://twitter.com/cfbolz/status/783313503230844929 .

**Comment by SylvainDe** [comment]
http://inventwithpython.com/blog/2012/07/09/16-common-python-runtime-errors/

**Comment by SylvainDe** [comment]
```
>>> 3.5 ^ 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for ^: 'float' and 'int'
>>> 3.5 ** 2
12.25

```

**Comment by SylvainDe** [comment]
```
>>> raise NotImplemented
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must be old-style classes or derived from BaseException, not NotImplementedType

```

A fuzzy match on the actual subclasses of BaseException could be nice :)

**Comment by SylvainDe** [comment]
`TypeError: unhashable instance`

Maybe suggest how to make the instance hashable (on custom classes), maybe suggest hashable types (`frozenset`, `tuple`, etc).

**Comment by SylvainDe** [comment]
https://mail.python.org/pipermail/python-ideas/2016-December/043910.html

**Comment by SylvainDe** [comment]
`RuntimeError: dictionary changed size during iteration`

http://stackoverflow.com/questions/11941817/how-to-avoid-runtimeerror-dictionary-changed-size-during-iteration-error

**Comment by SylvainDe** [comment]
http://stackoverflow.com/questions/19234598/typeerror-str-object-cannot-be-interpreted-as-an-integer

http://stackoverflow.com/questions/28036309/typeerror-list-object-cannot-be-interpreted-as-an-integer

**Comment by SylvainDe** [comment]
https://mail.python.org/pipermail/python-checkins/2015-October/139263.html

**Comment by SylvainDe** [comment]
This is an interesting issue and might deserve some suggestion : 
http://stackoverflow.com/questions/4545661/unicodedecodeerror-when-redirecting-to-file

**Comment by SylvainDe** [comment]
"TypeError: can only concatenate list (not "dict_keys") to list"

**Comment by SylvainDe** [comment]
`TypeError: argument to reversed() must be a sequence`

**Comment by SylvainDe** [comment]
http://stackoverflow.com/questions/41388606/python-3-6-vs-3-5-typeerror-message-on-string-concatenation

**Comment by SylvainDe** [comment]
I got this issue : http://stackoverflow.com/questions/24463202/typeerror-get-takes-no-keyword-arguments . Maybe suggesting position arguments and explaining that C-level API is exception to the usual rule is a good idea.

**Comment by SylvainDe** [comment]
http://sametmax.com/quelques-erreurs-tordues-et-leurs-solutions-en-python/

**Comment by SylvainDe** [comment]
http://darkf.github.io/posts/problems-i-have-with-python.html

**Comment by SylvainDe** [comment]
Idea: detection (?) and suggestion for circular import.

https://fr.reddit.com/r/Python/comments/5qxhcu/could_you_take_a_look_at_my_first_ever_python/?st=iyjta9cc&sh=5cd2c314

https://github.com/bndr/pycycle

https://docs.python.org/3/faq/programming.html#how-can-i-have-modules-that-mutually-import-each-other

https://docs.python.org/3/faq/programming.html#what-are-the-best-practices-for-using-import-in-a-module

**Comment by SylvainDe** [comment]
Idea: reuse `_moved_attributes` from https://github.com/benjaminp/six/blob/master/six.py (with proper attribution).

**Comment by SylvainDe** [comment]
Idea: use `gc.get_objects()` for various purposes (`get_func_by_name`, `get_type_by_name`, etc).

**Comment by SylvainDe** [comment]
https://twitter.com/sam_et_max/status/836551598054731776
https://twitter.com/sam_et_max/status/836551787058454529

**Comment by SylvainDe** [comment]
"TypeError: 'generator' object is not subscriptable" ->  itertools.islice(my_generator, 5)

**Comment by SylvainDe** [comment]
Set.remove keyerror set.discard

**Comment by SylvainDe** [comment]
Suggest using PYTHONIOENCODING n case of Encode/Decode error (when relevant - whatever it means, not always)

**Comment by SylvainDe** [comment]
http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap

**Comment by SylvainDe** [comment]
TypeError: Cannot create a consistent method resolution... http://stackoverflow.com/questions/29214888/typeerror-cannot-create-a-consistent-method-resolution-order-mro

**Comment by SylvainDe** [comment]
https://mail.python.org/pipermail/python-ideas/2017-June/046025.html
https://mail.python.org/pipermail/python-ideas/2017-June/045954.html

**Comment by SylvainDe** [comment]
Interesting thing already done : https://twitter.com/DRMacIver/status/912812300125577216?s=03 .

```
>>> sum(["a", "b", "c"], '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sum() can't sum strings [use ''.join(seq) instead]
```

**Comment by SylvainDe** [comment]
```
>>> set([42])[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'set' object does not support indexing

```

Maybe suggest `pop` ?

**Comment by SylvainDe** [comment]
```
>>> del s[42]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'set' object doesn't support item deletion
>>> s.remove(42)
>>> d = {43: 'x'}
>>> d.remove(43)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'remove'
>>> del d[43]
```

(Also `discard`)

**Comment by SylvainDe** [comment]
https://mail.python.org/pipermail/python-ideas/2017-July/046318.html

**Comment by SylvainDe** [comment]
https://twitter.com/DRMacIver/status/949956253358452736

**Comment by SylvainDe** [comment]
https://blog.lerner.co.il/favorite-terrible-python-error-message/

**Comment by SylvainDe** [comment]
Add tests for walrus operator

**Comment by SylvainDe** [comment]
Add suggestion for keyerror. I thought this was tackled already but apparently no

https://realpython.com/python-keyerror/

**Comment by SylvainDe** [comment]
Positional only arguments

**Comment by SylvainDe** [comment]
https://inventwithpython.com/blog/2019/08/15/python-error-messages-gotta-catch-em-all/

**Comment by SylvainDe** [comment]
KeyError on del on a dict. Should call pop ?

**Comment by SylvainDe** [comment]
https://twitter.com/cfbolz/status/1168979340601831424?s=19

**Comment by SylvainDe** [comment]
It looks like cfbolz really like to improve error messages: https://github.com/cfbolz/syntaxerrors . To be added to README eventually.
