### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tb_next'

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#21]
Following behavior to fix asap:

```
DidYouMean-Python/didyoumean $ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import didyoumean_api
>>> didyoumean_api.didyoumean_enablehook()
>>> return
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/josay/Geekage/NewNewDidYouMean/DidYouMean-Python/didyoumean/didyoumean_api.py", line 83, in didyoumean_hook
    add_suggestions_to_exception(type_, value, traceback)
  File "/home/josay/Geekage/NewNewDidYouMean/DidYouMean-Python/didyoumean/didyoumean_internal.py", line 656, in add_suggestions_to_exception
    traceback)))
  File "/home/josay/Geekage/NewNewDidYouMean/DidYouMean-Python/didyoumean/didyoumean_internal.py", line 586, in get_suggestions_for_exception
    frame = get_last_frame(traceback)
  File "/home/josay/Geekage/NewNewDidYouMean/DidYouMean-Python/didyoumean/didyoumean_internal.py", line 640, in get_last_frame
    while traceback.tb_next:
AttributeError: 'NoneType' object has no attribute 'tb_next'

Original exception was:
  File "<stdin>", line 1
SyntaxError: 'return' outside function
>>> 
```

**Comment by SylvainDe** [comment]
Closed by https://github.com/SylvainDe/DidYouMean-Python/commit/ae1382741f9fad58de73f79691a03ce47ef4ddbf .
