### ISSUE TITLE
Different regexp on Python 3.7-dev/nightly

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#28]
Error detected by Travis: https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/213076066

```
======================================================================
FAIL: test_no_implicit_str_conv2 (didyoumean_sugg_tests.TypeErrorTests)
Trying to concatenate a non-string value to a string.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 1663, in test_no_implicit_str_conv2
    self.throws(bad_code, MUSTBETYPENOTTYPE, [], after, 'cpython')
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 397, in throws
    self.assertRegexpMatches(msg, error_msg, details)
AssertionError: Running following code :
---
"things " + 12
---: '^must be ([\\w\\.-]+), not ([\\w\\.-]+)$' not found in 'can only concatenate str (not "int") to str'
```

**Comment by SylvainDe** [comment]
Introduced by : https://github.com/python/cpython/commit/004e03fb0c2febe2ec8afbd28ffcb3e980c63228

**Comment by SylvainDe** [comment]
Seems to be good now!
