### ISSUE TITLE
CI jobs failing on Python 3.2 / PyPy3

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#30]
Jobs have been failing fro a few days now:
 - https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/231646869
 - https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/231646886

```
2.59s$ pip install coverage==3.7.1
/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/_vendor/pkg_resources/__init__.py:80: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
Collecting coverage==3.7.1
  Downloading coverage-3.7.1.tar.gz (284kB)
    100% |████████████████████████████████| 286kB 1.9MB/s 
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/req/req_set.py", line 601, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/req/req_install.py", line 397, in run_egg_info
    self.setup_py, self.name,
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pip/req/req_install.py", line 372, in setup_py
    import setuptools  # noqa
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pkg_resources/__init__.py", line 77, in <module>
    raise RuntimeError("Python 3.3 or later is required")
RuntimeError: Python 3.3 or later is required
```

**Comment by SylvainDe** [comment]
Related issues:

 - https://github.com/pinterest/pymemcache/issues/132
 - https://github.com/pypa/pip/issues/3452
 - https://github.com/pypa/pip/issues/3390
 - https://github.com/travis-ci/travis-ci/issues/6304

**Comment by SylvainDe** [comment]
Last commit did not fix anything, the failure is just different : https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/231730380 .

```
$ pip install --upgrade pep8
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.6/bin/pip", line 7, in <module>
    from pip import main
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pip/_vendor/requests/__init__.py", line 66, in <module>
    from .models import Request, Response, PreparedRequest
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pip/_vendor/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

**Comment by yupbank** [comment]
Hey... i also come into the latter failure.. did you have a solution for that?

**Comment by SylvainDe** [comment]
@yupbank Not yet. I have a limited understanding on this and haven't found an obvious solution. Reading the issues linked above might lead to a solution but in any case, a general consensus seems to be that Python 3.2 is not supposed to be used. If you find anything, I am obviously interested :)

**Comment by yupbank** [comment]
Ah. I've found a solution.
add this `pip install tox-travis` and it will settle nasty things behind the virtualenv verison and python3.2 version

**Comment by yupbank** [comment]
ah.. nvm.. you are not using tox.. maybe i can port a pr for you.. if i have time..

**Comment by SylvainDe** [comment]
@yupbank Thanks for the feedback. If you do have time for a PR, that's brilliant. If you don't, a link to the commit(s) fixing the issue on your side would be much appreciated.

**Comment by yupbank** [comment]
sorry i was too busy.. try this https://github.com/SimonSapin/tinycss2/pull/6

**Comment by SylvainDe** [comment]
@yupbank Thank you very much! I'll have a look asap (after going through the doc to understand all of it). I'm glad you found something working for you :-)

**Comment by hugovk** [comment]
I think you can safely drop Python 3.2 now, it's been EOL for a while and its Unicode handling is a pain so many packages are dropping it.

![image](https://user-images.githubusercontent.com/1324225/31840782-84e5fbc4-b5ef-11e7-97ec-5b635ee98027.png)

https://en.wikipedia.org/wiki/CPython#Version_history

As for PyPy3, Travis have updated it to a later release which is based on later Python 3 version, so just try rebuilding it and it may well pass now.
