### ISSUE TITLE
New error on nightly build: didyoumean_internal_tests.AddStringToMemoryErrorTest

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#34]
After logging is improved, error is:

```
FAIL: test_add_string_to_repr (didyoumean_internal_tests.AddStringToMemoryErrorTest)
Non-empty string added to error's repr value.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_internal_tests.py", line 469, in test_add_string_to_repr
    repr, "ABCDErepr", self.prefix_repr, self.suffix_repr)
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_internal_tests.py", line 452, in check_string_added
    prefix + string + suffix, s1, s2, self.check_str_sum)
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_common_tests.py", line 94, in assertStringAdded
    self.assertIn(string, after)
AssertionError: "'ABCDErepr'," not found in "MemoryError('ABCDErepr')"
```

**Comment by SylvainDe** [comment]
Last OK: https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/332469454 ( Python 3.7.0a0 )
First KO: https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/332953835 ( Python 3.7.0a4+ )

**Comment by SylvainDe** [comment]
Last OK:
https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/332469454
https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/332469485 / https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/332469489
Python 3.7.0a0

First KO:
https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/332953835
https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/332953847 / https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/332953849
Python 3.7.0a4+

**Comment by SylvainDe** [comment]
Issue seems to be fixed. I'd like to find the explanation, I'll look for it later and keep the issue opened to remember it.

**Comment by SylvainDe** [comment]
Corresponding change is https://bugs.python.org/issue30399 / https://github.com/python/cpython/commit/f8a4c03ede6048022f60a58d5a21b278b78a8a16 .
So it is exactly what was intended :)

**Comment by SylvainDe** [comment]
For the reference, I've used git bisect to find the culprit. I've used something similar to what I did here: https://bugs.python.org/file46939/git_bisect_bpo30600.txt .
