### ISSUE TITLE
Test test_method_called_on_class fails on "recent" Python versions

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#36]
This used to be hidden because we were running unaffected versions of Python on Travis (dist: Trusty).
The recent changes in the travis.yml file ensure we run test on dist: xenial when relevant.
When this happens, we have the following error shows:

```
FAIL: test_method_called_on_class (didyoumean_sugg_tests.TypeErrorTests)
Test where a method is called on a class and not an instance.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 1262, in test_method_called_on_class
    self.throws(bad_code, err_cy, interpreters='cpython')
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 416, in throws
    self.assertRegexpMatches(msg, error_msg, details)
AssertionError: Running following code :
---
set.add(0)
---: "^descriptor '(\\w+)' requires a '([\\w\\.-]+)' object but received a '([\\w\\.-]+)'$" not found in "descriptor 'add' for 'set' objects doesn't apply to 'int' object"
```

See https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/488164466

Affected versions:
 - 3.7-dev: affects Python 3.7.2+ but not Python 3.7.0a4+
 - 3.7: affects Python 3.7.1
 - 3.8-dev: affects Python 3.8.0a0
 - nightly: it may affect Python 3.8.0a0 but not Python 3.7.0a4+

**Comment by SylvainDe** [comment]
Trying to find the corresponding commit...

Affected:

```
3.7 https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/488170149
$ python -VV
Python 3.7.1 (default, Dec  5 2018, 18:09:53) 
[GCC 5.4.0 20160609]
$ python -c "import sys; print(sys._git)" || true
('CPython', '', '')
```

```
3.7-dev https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/488170151
$ python -VV
Python 3.7.2+ (heads/3.7:cba16b7, Feb  3 2019, 07:27:51) 
[GCC 5.4.0 20160609]
$ python -c "import sys; print(sys._git)" || true
('CPython', 'heads/3.7', 'cba16b7')
```


Not affected

```
https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/488170150
$ python -VV
Python 3.7.0a4+ (heads/master:4666ec5, Jan 26 2018, 04:14:24) 
[GCC 4.8.4]
$ python -c "import sys; print(sys._git)" || true
('CPython', 'heads/master', '4666ec5')
```

**Comment by SylvainDe** [comment]
This limits the search to... 1666 commits...

```
$ git log --oneline 4666ec5..cba16b7 | wc
1666   15802  126485

```

**Comment by SylvainDe** [comment]
We could try to find more with git bisect:

```
$ cat bisect_script.sh
# Used with "git bisect run ./bisect_script.sh"
make clinic || return 125
make || return 125
make test TESTOPTS="-v test_issue36"
```

and
```
$ cat Lib/test/test_issue36.py
import unittest
import sys
from test.support import cpython_only


TYPE_NAME = r"[\w\.-]+"
FUNC_NAME = r"<?\w+>?"

NB_ARG_RE = r"^(?P<func>{0})(?:\(\) takes| expected) " \
    r"(?:exactly |at least |at most )?(?P<expected>no|\d+) " \
    r"(?:positional |non-keyword )?arguments?,? " \
    r"\(?(?:but |got )?(?P<actual>\d+)" \
    r"(?: were given| was given| given)?\)?" \
    r"(?:\. Did you forget 'self' in the function definition\?)?" \
r"$".format(FUNC_NAME)
DESCRIPT_REQUIRES_TYPE_RE = r"^descriptor '(\w+)' " \
    r"(?:requires a|for) '({0})' " \
    r"(?:object but received a|objects doesn't apply to) '({0})'" \
    r"(?:| object)$".format(TYPE_NAME)
DESCRIPT_REQUIRES_TYPE_RE = r"^descriptor '(\w+)' requires a '({0})' " \
    r"object but received a '({0})'$".format(TYPE_NAME)
ARG_NOT_ITERABLE_RE = r"^(?:argument of type )?'({0})'" \
    r"(?: object)? is not iterable$".format(TYPE_NAME)
MUST_BE_CALLED_WITH_INST_RE = r"^unbound method (\w+)\(\) must be called " \
    r"with ({0}) instance as first argument " \
    r"\(got ({0}) instance instead\)$".format(TYPE_NAME)


DESCREXPECT = (TypeError, DESCRIPT_REQUIRES_TYPE_RE)
MUSTCALLWITHINST = (TypeError, MUST_BE_CALLED_WITH_INST_RE)
NBARGERROR = (TypeError, NB_ARG_RE)
ARGNOTITERABLE = (TypeError, ARG_NOT_ITERABLE_RE)


# Logic to be able to have different tests on various version of Python
FIRST_VERSION = (0, 0)
LAST_VERSION = (10, 0)
ALL_VERSIONS = (FIRST_VERSION, LAST_VERSION)
INTERPRETERS = ['cpython', 'pypy']


def from_version(version):
    """Create tuple describing a range of versions from a given version."""
    return (version, LAST_VERSION)


def up_to_version(version):
    """Create tuple describing a range of versions up to a given version."""
    return (FIRST_VERSION, version)


def before_and_after(version):
    """Return a tuple with the version ranges before/after a given version.
    See also: before_mid_and_after, ranges_between.
    """
    return up_to_version(version), from_version(version)



def version_in_range(version_range):
    """Test if current version is in a range version."""
    beg, end = version_range
    return beg <= sys.version_info < end


def interpreter_in(interpreters):
    """Test if current interpreter is in a list of interpreters."""
    is_pypy = hasattr(sys, "pypy_translation_info")
    interpreter = 'pypy' if is_pypy else 'cpython'
    return interpreter in interpreters



def format_str(template, *args):
    """Format multiple string by using first arg as a template."""
    return [template.format(arg) for arg in args]


class PythonEnvRange(object):
    """Class to describe a (range of) Python environment.
    A range of Python environments consist of:
     - a range of Python version (tuple)
     - a list of interpreters (strings).
    """

    def __init__(self, version_range=None, interpreters=None):
        """Init a PythonEnvRange.
        The parameters are:
         - a range of version (optional - ALL if not provided)
         - a list of interpreters (optional - ALL if not provided).
            Also, a single interpreter can be provided.
        """
        self.interpreters = listify(interpreters, INTERPRETERS, str)
        self.version_range = \
            ALL_VERSIONS if version_range is None else version_range

    def contains_current_env(self):
        """Check if current environment is in PythonEnvRange object."""
        return version_in_range(self.version_range) and \
            interpreter_in(self.interpreters)


def listify(value, default, expected_types):
    """Return list from value, using default value if value is None."""
    if value is None:
        value = list(default)
    if not isinstance(value, list):
        value = [value]
    if default:
        assert all(v in default for v in value), "%s %s" % (value, default)
    if expected_types is not None:
        assert all(isinstance(v, expected_types) for v in value), \
            "%s %s" % (value, expected_types)
    return value


def get_exception(code):
    """Helper function to run code and get what it throws (or None)."""
    try:
        exec(code)
    except:
        return sys.exc_info()
    return None


class GetSuggestionsTests(unittest.TestCase):
    """Generic class to test get_suggestions_for_exception.
    Many tests do not correspond to any handled exceptions but are
    kept because it is quite convenient to have a large panel of examples.
    Also, some correspond to example where suggestions could be added, those
    are flagged with a NICE_TO_HAVE comment.
    Finally, whenever it is easily possible, the code with the suggestions
    taken into account is usually tested too to ensure that the suggestion does
    work.
    """

    def runs(self, code, version_range=None, interpreters=None):
        """Helper function to run code.
        version_range and interpreters can be provided if the test depends on
        the used environment.
        """
        details = "Running following code :\n---\n{0}\n---".format(code)
        if PythonEnvRange(version_range, interpreters).contains_current_env():
            exc = get_exception(code)
            self.assertTrue(exc is None, "Exc thrown : " + str(exc) + details)

    def throws(self, code, error_info,
               sugg=None, version_range=None, interpreters=None):
        """Run code and check it throws and relevant suggestions are provided.
        Helper function to run code, check that it throws, what it throws and
        that the exception leads to the expected suggestions.
        version_range and interpreters can be provided if the test depends on
        the used environment.
        """
        sugg = sorted(listify(sugg, [], str))
        error_type, error_msg = error_info
        details = "Running following code :\n---\n{0}\n---".format(code)
        if PythonEnvRange(version_range, interpreters).contains_current_env():
            exc = get_exception(code)
            self.assertFalse(exc is None, "No exc thrown." + details)
            type_caught, value, traceback = exc
            self.assertTrue(isinstance(value, type_caught))
            self.assertTrue(
                issubclass(type_caught, error_type),
                "{0} ({1}) not a subclass of {2}"
                .format(type_caught, value, error_type) + details)
            msg = next((a for a in value.args if isinstance(a, str)), '')
            if error_msg is not None:
                self.assertRegexpMatches(msg, error_msg, details)
            # suggestions = sorted(
            #     get_suggestions_for_exception(value, traceback))
            # self.assertEqual(suggestions, sugg, details)

class Toto(GetSuggestionsTests):

    def test_method_called_on_class(self):
        """Test where a method is called on a class and not an instance.
        Forgetting parenthesis makes the difference between using an
        instance and using a type.
        """
        # NICE_TO_HAVE
        wrong_type = (DESCREXPECT, MUSTCALLWITHINST, NBARGERROR)
        not_iterable = (ARGNOTITERABLE, ARGNOTITERABLE, ARGNOTITERABLE)
        before, after = before_and_after((3, 0))
        for code, (err_cy, err_pyp, err_pyp3) in [
                ('set{0}.add(0)', wrong_type),
                ('list{0}.append(0)', wrong_type),
                ('0 in list{0}', not_iterable)]:
            bad_code, good_code = format_str(code, '', '()')
            self.runs(good_code)
            self.throws(bad_code, err_cy, interpreters='cpython')
            self.throws(bad_code, err_pyp, [], before, 'pypy')
            self.throws(bad_code, err_pyp3, [], after, 'pypy')


if __name__ == "__main__":
    unittest.main()
```

**Comment by SylvainDe** [comment]
The more I investigate, the less I understand...

**Comment by SylvainDe** [comment]
https://stackoverflow.com/questions/54612348/different-error-message-when-unittest-assertraisesregex-is-called-as-a-context-m

https://bugs.python.org/issue35965

The issue might be related to ... coverage.

To be continued.

**Comment by SylvainDe** [comment]
Opened https://github.com/nedbat/coveragepy/issues/773 .

**Comment by SylvainDe** [comment]
And this may actually be a Python bug: https://bugs.python.org/issue35965 .

**Comment by SylvainDe** [comment]
Commit above was submitted leading to a new failure on CI for Python 3.8 / nightly:
https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/514941050
https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/514941052

Python version info:

```
$ python -VV
Python 3.8.0a3+ (heads/master:b8311cf, Apr  2 2019, 09:36:26) 
[GCC 5.4.0 20160609]
before_script.2
0.02s$ python -c "import sys; print(sys._git)" || true
('CPython', 'heads/master', 'b8311cf')
```


Error is:


```
======================================================================
FAIL: test_method_called_on_class (didyoumean_sugg_tests.TypeErrorTests)
Test where a method is called on a class and not an instance.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 1266, in test_method_called_on_class
    self.throws(bad_code, err_cy, interpreters='cpython')
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 419, in throws
    self.assertRegexpMatches(msg, error_msg, details)
AssertionError: Running following code :
---
set.add(0)
---: "^descriptor '(\\w+)' requires a '([\\w\\.-]+)' object but received a '([\\w\\.-]+)'$" not found in "descriptor 'add' for 'set' objects doesn't apply to a 'int' object"
----------------------------------------------------------------------
Ran 362 tests in 1.200s
FAILED (failures=1)

```

This was ok on the previous Travis run:

```
$ python -VV
Python 3.8.0a3+ (heads/master:42a139e, Apr  1 2019, 07:58:36) 
[GCC 5.4.0 20160609]
before_script.2
0.02s$ python -c "import sys; print(sys._git)" || true
```
