### ISSUE TITLE
Continuous integration: Different error message for test_object_indexing on recent Python builds

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#41]
```
FAIL: test_object_indexing (didyoumean_sugg_tests.TypeErrorTests)
Index from object does not work if __getitem__ is not defined.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 1821, in test_object_indexing
    self.throws(set_code,
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 417, in throws
    self.assertRegexpMatches(msg, error_msg, details)
AssertionError: Running following code :
---
set()[0]
---: "^\\'([\\w\\.-]+)\\' object (?:does not|doesn't) support (.*)$" not found in "'set' object is not subscriptable"
```

OK (Job 1452 https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/494645122 )
Python 3.7-dev - Python 3.7.2+ (heads/3.7:6f35219, Feb 17 2019, 07:35:15) 
Python 3.8-dev - Python 3.8.0a1+ (heads/master:414c625, Feb 17 2019, 07:35:57)
Python nightly - Python 3.7.0a4+ (heads/master:4666ec5, Jan 26 2018, 04:14:24) 

KO (Job 1453 https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/495186868 )
Python 3.7-dev - Python 3.7.2+ (heads/3.7:a7f929d, Feb 18 2019, 07:41:08) 
Python 3.8-dev - Python 3.8.0a1+ (heads/master:ac28147, Feb 18 2019, 07:36:23) 
Python nightly - Python 3.8.0a1+ (heads/master:ac28147, Feb 18 2019, 07:36:23)

Probably caused by https://github.com/python/cpython/commit/ac28147e78c45a6217d348ce90ca5281d91f676f .

**Comment by SylvainDe** [comment]
We have re.UNSUBSCRIPTABLE_RE instead of re.OBJ_DOES_NOT_SUPPORT_RE .

**Comment by SylvainDe** [comment]
Fixed
