### ISSUE TITLE
Continuous Integration on nightly during pep257 install: "ImportError: cannot import name 'Set' from 'collections'"

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#43]
First failing job:

https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/634043915

```
$ python -VV
Python 3.9.0a2+ (heads/master:b821173, Jan  7 2020, 18:49:21) 
[GCC 5.4.0 20160609]

$ python -c "import sys; print(sys._git)" || true
('CPython', 'heads/master', 'b821173')

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.9-dev/bin/pep257", line 5, in <module>
    from pep257 import main
  File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pep257.py", line 24, in <module>
    from collections import defaultdict, namedtuple, Set
ImportError: cannot import name 'Set' from 'collections' (/home/travis/virtualenv/python3.9-dev/lib/python3.9/collections/__init__.py)
The command "pep257 *.py */*.py" failed and exited with 1 during .
```

Last successful job:

https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/633568897

```
$ python -VV
Python 3.8.1+ (heads/3.8:6bf382a, Jan  2 2020, 12:08:12) 
[GCC 5.4.0 20160609]
$ python -c "import sys; print(sys._git)" || true
('CPython', 'heads/3.8', '6bf382a')
```

**Comment by SylvainDe** [comment]
Could this be related to https://bugs.python.org/issue37324 ?

**Comment by SylvainDe** [comment]
See also https://bugs.python.org/issue25988 .

In pydocstyle (pep257):

- https://github.com/PyCQA/pydocstyle/commit/7f5303c8f9c19010253e350a8d513c0f330226a0 introduces a workaround for this issue

 - https://github.com/PyCQA/pydocstyle/commit/c20721b8978812a81b49fc602538ee28577c5b76 gets rid of the old version and only keeps the new one

**Comment by SylvainDe** [comment]
For what it's worth, Jenkins seems to use pep257 0.7.0 which probably corresponds to https://github.com/PyCQA/pydocstyle/commit/d7d21b1008556df728be3993ebdd62abe17f1fcb (which is old)

**Comment by SylvainDe** [comment]
https://github.com/SylvainDe/DidYouMean-Python/commit/1c2afe98867212b6351f7cd10b487529986672eb "solved" the issue (I still need to fix the warnings and get rid of the pep257 mentions).

Now, the job fails later, on a similar issue, on unittest2.
For instance: 

```
  File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/unittest2/__init__.py", line 40, in <module>

    from unittest2.collector import collector

  File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/unittest2/collector.py", line 3, in <module>

    from unittest2.loader import defaultTestLoader

  File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/unittest2/loader.py", line 13, in <module>

    from unittest2 import case, suite, util

  File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/unittest2/case.py", line 18, in <module>

    from unittest2 import result

  File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/unittest2/result.py", line 10, in <module>

    from unittest2.compatibility import wraps

  File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/unittest2/compatibility.py", line 143, in <module>

    class ChainMap(collections.MutableMapping):

AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by SylvainDe** [comment]
After many tries, things seem to be working as far as this bug is concerned.
Another issue is now detected but it is a relevant one.
