### ISSUE TITLE
Continuous Integration on nightly (Python 3.9): error in test_c_func_takes_no_keyword_arguments: re does not match

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#44]
First failure: https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/634507305

```
Traceback (most recent call last):
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 1624, in test_c_func_takes_no_keyword_arguments
    self.throws(bad_code, NOKWARGS, sugg, interpreters='cpython')
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 431, in throws
    self.assertRegexpMatches(msg, error_msg, details)
AssertionError: Regex didn't match: '^(?P<func><?\\w+>?)(?:\\(\\))? (?:takes no|does not take) keyword arguments$' not found in 'dict.get() takes no keyword arguments' : Running following code :
---
dict().get(0, default=None)
---
```

We expect `get()` to be in the error message but we have `dict.get()`.
I do not quite know the best way to solve this issue.

**Comment by SylvainDe** [comment]
Related to https://github.com/python/cpython/commit/bf17d41826a8bb4bc1e34ba6345da98aac779e41
