### ISSUE TITLE
Continous Integration on 3.10.0-alpha.1: AttributeError when coverage is used

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#59]
**First failure**

Date: 3rd January 2023
Build: https://github.com/SylvainDe/DidYouMean-Python/actions/runs/3825929734
Jobs: https://github.com/SylvainDe/DidYouMean-Python/actions/runs/3825929734/jobs/6509299420

```
Python 3.10.0a1 (default, Jan 25 2021, 13:28:12) 
[GCC 9.3.0]
sys.version_info(major=3, minor=10, micro=0, releaselevel='alpha', serial=1)
```

```
Collecting coverage
  Downloading coverage-7.0.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.4/224.4 kB 12.2 MB/s eta 0:00:00
Installing collected packages: coverage
Successfully installed coverage-7.0.2
```

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.0-alpha.1/x64/bin/coverage", line 5, in <module>
    from coverage.cmdline import main
  File "/opt/hostedtoolcache/Python/3.10.0-alpha.1/x64/lib/python3.10/site-packages/coverage/__init__.py", line 15, in <module>
    from coverage.control import Coverage, process_startup
  File "/opt/hostedtoolcache/Python/3.10.0-alpha.1/x64/lib/python3.10/site-packages/coverage/control.py", line 37, in <module>
    from coverage.inorout import InOrOut
  File "/opt/hostedtoolcache/Python/3.10.0-alpha.1/x64/lib/python3.10/site-packages/coverage/inorout.py", line 29, in <module>
    from coverage.python import source_for_file, source_for_morf
  File "/opt/hostedtoolcache/Python/3.10.0-alpha.1/x64/lib/python3.10/site-packages/coverage/python.py", line 18, in <module>
    from coverage.parser import PythonParser
  File "/opt/hostedtoolcache/Python/3.10.0-alpha.1/x64/lib/python3.10/site-packages/coverage/parser.py", line 26, in <module>
    from coverage.phystokens import generate_tokens
  File "/opt/hostedtoolcache/Python/3.10.0-alpha.1/x64/lib/python3.10/site-packages/coverage/phystokens.py", line 78, in <module>
    class MatchCaseFinder(ast.NodeVisitor):
  File "/opt/hostedtoolcache/Python/3.10.0-alpha.1/x64/lib/python3.10/site-packages/coverage/phystokens.py", line 86, in MatchCaseFinder
    def visit_Match(self, node: ast.Match) -> None:
AttributeError: module 'ast' has no attribute 'Match'
Error: Process completed with exit code 1.
```

**Last success**

Date: 2nd January 2023
Build: https://github.com/SylvainDe/DidYouMean-Python/actions/runs/3819391401
Jobs: https://github.com/SylvainDe/DidYouMean-Python/actions/runs/3819391401/jobs/6496911544

```
Python 3.10.0a1 (default, Jan 25 2021, 13:28:12) 
[GCC 9.3.0]
sys.version_info(major=3, minor=10, micro=0, releaselevel='alpha', serial=1)
```

```
 Collecting coverage
  Downloading coverage-7.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.0/216.0 kB 25.7 MB/s eta 0:00:00
Installing collected packages: coverage
Successfully installed coverage-7.0.1
```

**Comment by SylvainDe** [comment]
It most probably relates to commit https://github.com/nedbat/coveragepy/commit/cceadff1d3d33c046042b606d40e01f41e23ec5d and to lines https://github.com/nedbat/coveragepy/blob/master/coverage/phystokens.py#L85 in particular.
